packageExtensions:
  "chartjs-node-canvas@*":
    dependencies:
      "canvas": "*"
  "canvas@*":
    dependencies:
      "fs": "*"
      "path": "*"
      "util": "*"
yarnPath: .yarn/releases/yarn-3.5.0.cjs
